---
title: "On the Measurement of Virtue using National-scale Panel Data"
author: 
  - name: Joseph Bulbulia
    orcid: 0000-0002-5861-2056
    affiliation: Victoria University of Wellington,  New Zealand
    corresponding: yes
    address: Victoria University of Wellington, New Zealand
    email: joseph.bulbulia@vuw.ac.nz

format: html
title-block-style: plain
bibliography: references.bib
date: 2022-11-02
date-format: short
citation: true
execute:
  echo: false
  warning: false
  message: false
  error: false
---

## Introduction

Religious traditions span the full bandwidth of human diversity. Despite their differences nearly all religious traditions agree that life's greatest goods come from virtuous living. Moreover, religious traditions hold that the practice of religion is itself a virtue. For example, in classical Christian thought, the religion is a virtue of justice, consisting of acts and prayers, that appropriately acknowledges God as the source of our existence and continuance [@aquinas1702]. Might the causes and consequences of virtuous living form the object of scientific inquiry? And if so, for whom might such a science prove interesting?

This article has three objectives.

First, I consider credible objections to the proposal that the causes and consequences of virtuous living can form the objects of scientific study.

<!-- If the cultivation of virtue, including the virtue of religion, indeed makes life good, and if the good in life is apparent, then in theory the causes and consequences of virtue should be observable and amenable to scientific study. -->

Second, I argue for a pragmatic position that (1) accepts the credible objections against a scientific study of virtue ; (2) remains open to the possibility that the scientific study of virtue may prove interesting, and even edifying, for both scientific and religious audiences.

Finally, I reflect on specifically how the scientific study of virtue might prove interesting or even edifying to scientific and religious audiences.

I will restrict my interest to to the promise, and perils, of national-scale longitudinal psychology. I focus on longitudional psychology because it is the science I know best through my experiences as a researcher for the New Zealand Attitudes and Values Study ([NZAVS](https://www.psych.auckland.ac.nz/en/about/new-zealand-attitudes-and-values-study.html)).

## Objections to virtue science

Consider the following credible objections against a psychological science of virtue.

The first credible to the psychological science of virtue is conceptual. Psychological scientists study how people think and behave. However, in classical philosophical and religious reflection, virtue is presented as a skill. As such, virtue is subject both to deficiencies and excesses. For example, Aristotle held that deficiency in the virtue of courage is cowardice and the excess in the virtue of courage is rashness. Aristotle also held that deficiency in the virtue of temperance is indulgence and its excess is insensibility [@pakaluk2005]. If virtue is a skill, to perceive virtue would require, at least in some cases, to possess the virtue. Consider an analogy to music. To assess the quality of a jazz musician requires competence in the genre of Jazz. Although we may study jazz from a behavioral or cognitive perspective such a study would not carry us to an appreciation of excellence in the genre. Similarly, it is unclear how the scientific study of human thought and behavior would carry us to an appreciation of moral excellence. A rash scientist might judge rash behavior as courageous. If religion is indeed a virtue, one that is prone to excesses and deficiencies, then the qualities that distinguish the virtue of religion from, say, the vices of idolatry or indifference, might not be available to scientific inquiry.

A second credible challenge to the psychological science of virtue is practical. Suppose that virtue is not hidden to science. Nevertheless, it is credible that we might not be able to describe virtue in a language of scientific measurement. William James writes, "Philosophy lives in words, but truth and fact well up into our lives in ways that exceed verbal formulation. There is in the living act of perception always something that glimmers and twinkles and will not be caught, and for which reflection comes too late" [@james1902, pp.456-457]. A similar observation might be made about the scientific study of virtue. Is the recognition of virtue something that can be characterised in the language of science? If virtue pertains to experiences that are poorly represented in human language, it would seem that science will inevitably misconceive the experiential qualities of virtue as it is experienced.

A third credible challenge to the psychological science of virtue relates to the scope of psychological science. The gold standard for research design in psychological science is an idealised "random experiment." Assignment to a treatment condition or a control condition is by change. An average response is taken withing groups. If the average response differs by condition, we say that the treatment has a causal effect. As mentioned, the inference one obtains from a randomised experiment pertains to the *average* response. Unless the population is homogenous in its response, there will be those individuals who respond higher as well as those that respond lower than average [@bulbulia2022; @hernan2023]. Although the average response is the Holy Grail of psychological science, teachers and students of virtue typically want to know what works for specific individuals. It would therefore seem that the psychological science of virtue holds limited practical interest.

Notice that I did not consider the objection that science assumes that virtue is unreal. I will return to this consideration below.

## Responses to objections

I describe the preceding objections to a psychological science of virtue as "credible" because they are persuasive and we should believe them. A psychological science of virtue must begin with a sober appreciation of what the science cannot deliver.

First, a psychological science of virtue cannot substitute for the cultivation of virtue. Just as a medical doctor need not be physically fit to heal, so too psychological scientists need not be virtuous to study virtue. Longitudinal psychology measures people over time. It systematically investigates how beliefs and habits affect people. However, a researcher can no more lay claim to asserting virtue than a tap recorder can lay claim to musical virtuosity. Once recorded, however, it might be possible for musical experts to spot virtuosity.

Second, we must appreciate that psychological science of virtue is limited in the scope of knowledge that it can afford. However, knowledge may grow without reaching its limit. We would set too high an expectation on science if we to require that it captures more than a small fraction of what makes virtue worthwhile.

Third, we must recognise that longitudinal psychological science investigates average effects in populations. There is no psychological science of individual-level causes and effects. Teachers and students of virtues should indeed be weary of thoughtlessly applying the results of any scientific study of virtue to some practical task. However, here again the average response might nevertheless prove interesting and afford some guidance. For example, we know that on average medically approved vaccines help more people than they harm. Some unlucky people will suffer worse harms from taking vaccine that they would have had they abstained. Nevertheless, must of us will hedge our bets, noticing that a far greater number of people are harmed from abstaining. We roll the dice, but the dice are loaded in our favor. It remains an open question whether the study of average effects might prove useful.

If the arguments against a psychological science of virtue are taken as sensible limitations on the boundaries of what it might deliver, I believe that the psychological science of virtue can be interesting and indeed edifying. To make this case it is useful to describe how a psychological science of virtue might work.

## Christchurh Earthquake example. 



## The practical interest of longitudinal virtue science for different audiences

### Interest for human scientists

Virtue as the topic for health.

### Interest for theologians

Good theology begins with facts.

### Interest for teachers and clergy

Averages can be useful. Science broadens experience beyond the particulars.

## Conclusions

## References
